# Generated by Django 4.1.7 on 2023-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_message_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subtopic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
