# Generated by Django 4.1.7 on 2023-06-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_room_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='subtopic',
        ),
    ]
