# Generated by Django 4.0.3 on 2024-08-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_chat_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
